spring.application.name=DigitalBillingSystem
spring.datasource.url=jdbc:mysql://localhost:3306/billing_db
spring.datasource.username=root
spring.datasource.password=Setu@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
